"""
schemas.py
----------
Single Responsibility: Define Pydantic v2 models for the API contract.

These schemas act as the border patrol for the API. They control exactly
what JSON comes IN (validation) and what JSON goes OUT (serialization).

Modules defined here:
  - Specialties  : SpecialtyBase, SpecialtyCreate, SpecialtyOut
  - Staff        : StaffBase, StaffOut, StaffSelfUpdate, StaffContactOut
  - Vacation     : VacationBase, VacationPostCreate, VacationPostResponse,
                   VacationStaffUpdate, VacationCanceled,
                   VacationDetails, VacationBalanceCreate, VacationBalanceResponse
"""

from pydantic import BaseModel, Field, field_validator, ConfigDict, EmailStr, model_validator
from typing import Optional
from datetime import datetime, date


# ============================================================================
# SPECIALTIES MODULE
# ============================================================================

class SpecialtyBase(BaseModel):
    """
    Shared fields used by both input and output schemas.

    Why a base class?
    DRY (Don't Repeat Yourself). The `name` and `description` fields exist
    on both the input (what the client sends) and the output (what we send back).
    Instead of typing them out twice and risking them getting out of sync,
    we define them once here and inherit them.
    """
    name: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Name of the medical specialty (e.g. Cardiology)",
        examples=["Cardiology"],
    )
    description: Optional[str] = Field(
        default=None,
        description="Optional detailed description",
        examples=["Complete care of the heart"],
    )


class SpecialtyCreate(SpecialtyBase):
    """
    Schema exclusively for POST /specialties incoming JSON bodies.
    Inherits `name` and `description` from SpecialtyBase.
    Notice it does NOT have an `id` field — the client doesn't dictate the ID.
    """
    @field_validator("name")
    @classmethod
    def name_must_not_be_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("Specialty name cannot be empty or just whitespace.")
        return value.strip()


class SpecialtyOut(SpecialtyBase):
    """
    Schema exclusively for outgoing JSON API responses.
    Inherits `name` and `description` from SpecialtyBase.
    Adds the `id` field, which was generated by the database.
    """
    id: int = Field(description="Auto-generated unique database ID")
    created_at: datetime = Field(description="Timestamp of creation")
    model_config = ConfigDict(from_attributes=True)


# ============================================================================
# STAFF MODULE
# ============================================================================

class StaffBase(BaseModel):
    """
    Shared fields for Staff input/output.
    These represent the main contact information and relationships.
    """
    first_name: str = Field(..., description="Employee's first name")
    last_name: str = Field(..., description="Employee's last name")
    email: str = Field(..., description="Employee's email address")
    phone_number: Optional[str] = Field(None, description="Employee's phone number")
    role_level: Optional[str] = Field(None, description="Role level or position")
    status: Optional[str] = Field(None, description="Current status (e.g., Online/Offline)")
    department: Optional[str] = Field(None, description="Department name")
    specialty: Optional[str] = Field(None, description="Specialty name")


class StaffOut(StaffBase):
    """
    Schema for API responses.
    Includes database-generated fields like id and created_at.
    """
    id: int = Field(..., description="Unique staff ID")
    created_at: datetime = Field(..., description="Timestamp of record creation")
    model_config = ConfigDict(from_attributes=True)


class StaffSelfUpdate(BaseModel):
    staff_id: int = Field(..., description="ID del empleado que realiza el cambio")
    email: Optional[EmailStr] = Field(None, description="Nuevo email")
    phone_number: Optional[str] = Field(None, description="Nuevo teléfono")
    profile_pic: Optional[str] = Field(None, description="URL de la foto")

    # Seguridad: Si el JSON trae 'role_level', FastAPI lo rechazará automáticamente.
    model_config = ConfigDict(extra="forbid")


class StaffContactOut(BaseModel):
    id: int
    first_name: str
    last_name: str
    email: EmailStr
    phone_number: str | None = None
    role_level: str | None = None
    status: str | None = None
    profile_pic: str | None = None
    department: str | None = None
    specialty: str | None = None
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)

class StaffCreate(BaseModel):
    user_id: int
    first_name: str
    last_name: str
    phone_number: Optional[str] = None
    start_date: date
    status: str
    role_level: str
    department_id: int
    specialty_id: Optional[int] = None
    profile_pic: Optional[str] = None
    vacation_details: Optional[dict] = None

class StaffUpdate(BaseModel):
    first_name: Optional[str] = Field(None, min_length=1, max_length=100)
    last_name: Optional[str] = Field(None, min_length=1, max_length=100)
    phone_number: Optional[str] = None
    status: Optional[str] = None
    role_level: Optional[str] = None
    department_id: Optional[int] = None
    specialty_id: Optional[int] = None
    profile_pic: Optional[str] = None

class StaffResponse(BaseModel):
    id: int
    user_id: int
    first_name: str
    last_name: str
    email: Optional[EmailStr] = None
    phone_number: Optional[str]
    start_date: date
    status: str
    role_level: str
    department_id: int
    specialty_id: Optional[int]
    profile_pic: Optional[str]
    vacation_details: Optional[dict]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

    @model_validator(mode='before')
    @classmethod
    def extract_email(cls, data):
        """Extrae el email de la tabla Users automáticamente"""
        if hasattr(data, 'user') and data.user:
            data.email = data.user.email
        return data
# --- AGREGAR ESTO AL FINAL DE LA SECCIÓN STAFF ---

class StaffCreate(BaseModel):
    user_id: int = Field(..., description="ID del usuario en la tabla users")
    first_name: str
    last_name: str
    phone_number: str | None = None
    start_date: date
    status: str = Field(default="Active")
    role_level: str
    department_id: int
    specialty_id: int | None = None
    profile_pic: str | None = None
    vacation_details: dict | None = None

class StaffUpdate(BaseModel):
    first_name: str | None = Field(None, min_length=1, max_length=100)
    last_name: str | None = Field(None, min_length=1, max_length=100)
    phone_number: str | None = None
    status: str | None = None
    role_level: str | None = None
    department_id: int | None = None
    specialty_id: int | None = None
    profile_pic: str | None = None

# ============================================================================
# VACATION MODULE
# ============================================================================

class VacationBase(BaseModel):
    """
    Shared fields used by both create and edit vacation schemas.
    These are the fields the employee provides when submitting or editing a request.
    """
    start_date: date = Field(description="First day of the vacation")
    end_date: date = Field(description="Last day of the vacation")
    comment: Optional[str] = Field(default=None, max_length=255)
    attachment_url: Optional[str] = Field(default=None, max_length=255)
    attachment_name: Optional[str] = Field(default=None, max_length=255)


class VacationPostCreate(VacationBase):
    """Schema for POST /myprofile/requestvacation — employee submits a new request."""
    pass


class VacationPostResponse(VacationBase):
    """
    Schema for all vacation API responses.
    Includes DB-generated fields: id, staff_id, request_date, status, reason, rejection_reason.
    """
    model_config = ConfigDict(from_attributes=True)
    id: int
    staff_id: int
    request_date: date
    reason: str
    status: str
    rejection_reason: Optional[str] = Field(default=None)


class VacationStaffUpdate(BaseModel):
    """Schema for PATCH /human-resources/vacation-management/{id} — HR approves or rejects."""
    rejection_reason: Optional[str] = Field(default=None, max_length=255)
    status: Optional[str] = Field(default="pending", max_length=20)


class VacationCanceled(BaseModel):
    """Schema for PATCH /myprofile/requestvacation/{id}/cancel — employee cancels."""
    status: Optional[str] = Field(default="cancelled")


class VacationDetails(BaseModel):
    """Vacation balance breakdown: assigned, used, available days."""
    assigned: int
    used: int
    available: int


class VacationBalanceCreate(BaseModel):
    """Input schema for assigning a vacation balance to a staff member."""
    vacation_details: VacationDetails


class VacationBalanceResponse(BaseModel):
    """Output schema for GET /myprofile/requestvacation/balance/{staff_id}."""
    model_config = ConfigDict(from_attributes=True)
    vacation_details: VacationDetails
